services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker1:
    image: confluentinc/cp-server:7.5.0
    hostname: broker1
    container_name: broker1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:19092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_JMX_OPTS: >-
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote.rmi.port=9989
        -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar=9994:/opt/jmx_exporter/jmx_exporter_config.yml
      JMX_PORT: 9989
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar:/opt/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar
      - /opt/jmx_exporter/jmx_exporter_config.yml:/opt/jmx_exporter/jmx_exporter_config.yml
    ports:
      - "9092:9092"
      - "9989:9989"
      - "9994:9994" # JMX Exporter metrics port

  broker2:
    image: confluentinc/cp-server:7.5.0
    hostname: broker2
    container_name: broker2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:19093,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19093,EXTERNAL://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_JMX_OPTS: >-
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote.rmi.port=9992
        -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar=9995:/opt/jmx_exporter/jmx_exporter_config.yml
      JMX_PORT: 9992
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar:/opt/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar
      - /opt/jmx_exporter/jmx_exporter_config.yml:/opt/jmx_exporter/jmx_exporter_config.yml
    ports:
      - "9093:9093"
      - "9992:9992"
      - "9995:9995" # JMX Exporter metrics port

  broker3:
    image: confluentinc/cp-server:7.5.0
    hostname: broker3
    container_name: broker3
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:19094,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19094,EXTERNAL://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_JMX_OPTS: >-
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=localhost
        -Dcom.sun.management.jmxremote.rmi.port=9988
        -javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar=9996:/opt/jmx_exporter/jmx_exporter_config.yml
      JMX_PORT: 9988
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar:/opt/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar
      - /opt/jmx_exporter/jmx_exporter_config.yml:/opt/jmx_exporter/jmx_exporter_config.yml
    ports:
      - "9094:9094"
      - "9988:9988"
      - "9996:9996" # JMX Exporter metrics port

  init-kafka:
    image: confluentinc/cp-server:7.5.0
    depends_on:
      - broker1
      - broker2
      - broker3
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      sleep 15
      /usr/bin/kafka-topics --create --topic topic1 --partitions 3 --replication-factor 3 --bootstrap-server broker1:19092
      /usr/bin/kafka-topics --create --topic topic2 --partitions 3 --replication-factor 3 --bootstrap-server broker1:19092
      /usr/bin/kafka-topics --create --topic topic3 --partitions 3 --replication-factor 3 --bootstrap-server broker1:19092
      kafka-topics --bootstrap-server broker1:19092 --list
      "

